gamerule keepinventory true
gamerule domobspawning false
gamerule showbordereffect false
gamerule dodaylightcycle false
gamerule doweathercycle false
gamerule doimmediaterespawn true
gamerule showtags false